lab5/Controllers/CountryController.cs
using Microsoft.AspNetCore.Mvc;
using lab5.Services;

namespace lab5.Controllers
{
    public class CountryController : Controller
    {
        private readonly ApiService _apiService;

        public CountryController(ApiService apiService)
        {
            _apiService = apiService;
        }

        public async Task<IActionResult> Index()
        {
            var countries = await _apiService.GetCountriesAsync();
            return View(countries);
        }
    }
}

lab5/Controllers/LocationController.cs
using Microsoft.AspNetCore.Mvc;
using lab5.Services;

namespace lab5.Controllers
{
    public class LocationController : Controller
    {
        private readonly ApiService _apiService;

        public LocationController(ApiService apiService)
        {
            _apiService = apiService;
        }

        public async Task<IActionResult> Index()
        {
            var locations = await _apiService.GetLocationsAsync();
            return View(locations);
        }
    }
}

lab5/Controllers/MovementLocationController.cs
using Microsoft.AspNetCore.Mvc;
using lab5.Services;

namespace lab5.Controllers
{
    public class MovementLocationController : Controller
    {
        private readonly ApiService _apiService;

        public MovementLocationController(ApiService apiService)
        {
            _apiService = apiService;
        }

        public async Task<IActionResult> Index()
        {
            var movementLocations = await _apiService.GetMovementLocationsAsync();
            return View(movementLocations);
        }
    }
}

lab5/Controllers/OrganizationController.cs
using Microsoft.AspNetCore.Mvc;
using lab5.Services;

namespace lab5.Controllers
{
    public class OrganizationController : Controller
    {
        private readonly ApiService _apiService;

        public OrganizationController(ApiService apiService)
        {
            _apiService = apiService;
        }

        public async Task<IActionResult> Index()
        {
            var organizations = await _apiService.GetOrganizationsAsync();

            return View(organizations);
        }
    }
}

lab5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - lab5</title>
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    <header>
        <nav>
            <div class="navbar">
                <a class="btn btn-primary" asp-area="" asp-controller="Home" asp-action="Index">lab5</a>
                <ul>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="dropdown">
                            <p class="btn btn-primary">Лабораторні роботи</p>
                            <div class="dropdown-menu">
                                <a asp-controller="Lab" asp-action="Lab1">Лаб 1</a>
                                <a asp-controller="Lab" asp-action="Lab2">Лаб 2</a>
                                <a asp-controller="Lab" asp-action="Lab3">Лаб 3</a>
                            </div>
                        </li>

                        <li class="dropdown">
                            <p class="btn btn-primary">Таблиці Лаб 6</p>
                            <div class="dropdown-menu">
                                <a asp-controller="ProductsAndServices" asp-action="Index">ProductsAndServices</a>
                                <a asp-controller="Organization" asp-action="Index">Organization</a>
                                <a asp-controller="Country" asp-action="Index">Country</a>
                                <a asp-controller="Location" asp-action="Index">Location</a>
                                <a asp-controller="MovementLocation" asp-action="Index">MovementLocation</a>
                            </div>
                        </li>

                        <li class="dropdown">
                            <p class="btn btn-primary">Акаунт</p>
                            <div class="dropdown-menu">
                                <a asp-controller="Home" asp-action="Profile">Профіль</a>
                                <a asp-controller="Account" asp-action="Logout">Вийти</a>
                            </div>
                        </li>
                    }
                    else
                    {
                        <li>
                            <a class="nav-link" asp-controller="Account" asp-action="Login">
                                <i class="fa fa-sign-in"></i> Увійти
                            </a>
                        </li>
                    }
                </ul>
            </div>
        </nav>
    </header>
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
    
</body>
</html>